apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30000
  selector:
    app: redis


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight-deployment
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redislabs/redisinsight:latest
          ports:
            - containerPort: 5540
          env:
            - name: RI_DATABASE_URL
              value: "redis://192.168.49.2:30000"


---


apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
spec:
  selector:
    app: redisinsight
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5540
      nodePort: 30001